name: AWS Automation

on:
  push:
    branches:
      - main

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install boto3

      - name: Executar script
        run: python listar_ec2.py